server {
    listen 80;
    root /usr/share/nginx/html;

    # Redirige la raíz al idioma español por defecto
    location = / {
        return 302 /es/;
    }

    # Español: sirve dist/browser/es/
    location /es/ {
        alias /usr/share/nginx/html/es/;
        try_files $uri $uri/ /es/index.html;
    }

    # Inglés: sirve dist/browser/en/
    location /en/ {
        alias /usr/share/nginx/html/en/;
        try_files $uri $uri/ /en/index.html;
    }
}
